version: "3"

services:
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
  prometheus:
    image: prom/prometheus:v2.9.1
    volumes:
      - promdata:/prometheus-data
      - ./prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  node-exporter:
    image: prom/node-exporter:v0.17.0
    ports:
      - 9100:9100

volumes:
  pgdata:
  promdata:
