version: "3"

services:
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
  # postgres-exporter:
  #   image: wrouesnel/postgres_exporter:v0.4.7
  # haproxy:
  #   image: haproxy:1.9-alpine
  # haproxy-exporter:
  #   image: prom/haproxy-exporter:v0.10.0
  # consul:
  #   image: consul:1.4.4
  # consul-exporter:
  #   image: prom/consul-exporter:v0.4.0
  prometheus:
    image: prom/prometheus:v2.9.1
    volumes:
      - promdata:/prometheus-data
      - ./prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  # node exporter won't show anything interesting since it
  # runs in a container, but still, purely as an example ...
  # it's ok
  node-exporter:
    image: prom/node-exporter:v0.17.0
    ports:
      - 9100:9100
  # alertmanager:
  #   image: prom/alertmanager:v0.16.2
  #   ports:
  #     - 9093:9093
  grafana:
    image: grafana/grafana:6.1.4
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      # - ./grafana/:/etc/grafana
      - grafanadata:/var/lib/grafana
volumes:
  pgdata:
  promdata:
  grafanadata:
