global:
  scrape_interval: 10s
  evaluation_interval: 10s
rule_files:
  - rules.yml
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#             - host.docker.internal:9093
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  - job_name: node
    static_configs:
      - targets:
          - node-exporter:9100
  - job_name: app
    static_configs:
      - targets:
          # https://docs.docker.com/docker-for-mac/networking/
          - host.docker.internal:4000
